<?php 
session_start();
/*if(isset($_POST['subject'])&&isset($_POST['message']))
{
    $to="sshanu95@gmail.com";
    $subject= $_POST["subject"]; 
    $message= $_POST["message"]; 
*/function email()
{
     if(isset($_SESSION['user_id'])&&!empty($_SESSION['user_id']))
			{
         if(!empty($_POST["subject"])&&!empty($_POST["message"]))
    {
        $to="htmlcsstutorials1@gmail.com";
        $subject= $_POST["subject"]; 
        $message= $_POST["message"];
        $from = $_SESSION['email'];
        $headers = "From:" . $from;
                if(mail($to,$subject,$message,$headers))
                {
                    $to=$_SESSION["email"];
                    $subject= "Auto Acknowledgement"; 
                    $message= "Dear Customer,

Thank you for writing to HCSTutorials. This is an automated response to your e-mail. We will respond to you within 1-2 working days.

Create your Account today at http://localhost/bootstrap/index.php.
 
Happy to help,

HCSTUTORIALS Care
";
                    $from = "acknowledgements@hcstutorials.com";
                    $headers = "From:" . $from;
                    if(mail($to, $subject, $message, $headers))
                    {//echo 'An Autogenerated mail has ben sent<br>Please check your mail!!<br>';
                   // header("Location:details.php");
                    $_SESSION['success_msg']="An Autogenerated mail has ben sent.Please check your mail!!";
                    echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
                    }else{
                       // echo 'We are facing a problem right now we will contact you shortly!!';
                        $_SESSION['fail_msg']="We are facing a problem right now we will contact you shortly!!";
                        echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
                    }
                }else {
            //echo 'Email could not be sent. Try after some time';
            $_SESSION['fail_msg']="Email could not be sent. Try after some time";
            echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
        }
            }else{
                //echo 'Please fill in all the fields';
                $_SESSION['fail_msg']="Please fill in all the fields";
                echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
}
     }
     else
     {
    if(!empty($_POST["subject"])&&!empty($_POST["message"])&&!empty($_POST["email"]))
    {
        $to="htmlcsstutorials1@gmail.com";
        $subject= $_POST["subject"]; 
        $message= $_POST["message"];
        $from = $_POST["email"];
        $headers = "From:" . $from;
                if(mail($to,$subject,$message,$headers))
                {
                    $to=$_POST["email"];
                    $subject= "Auto Acknowledgement"; 
                    $message= "Dear Customer,

Thank you for writing to HCSTutorials. This is an automated response to your e-mail. We will respond to you within 1-2 working days.

Create your Account today at https://localhost/bootstrap/index.php.
 
Happy to help,

HCSTUTORIALS Care
";
                    $from = "acknowledgements@hcstutorials.com";
                    $headers = "From:" . $from;
                    if(mail($to, $subject, $message, $headers))
                    {//echo 'An Autogenerated mail has ben sent<br>Please check your mail!!<br>';
                   // header("Location:details.php");
                    $_SESSION['success_msg']="An Autogenerated mail has ben sent.Please check your mail!!";
                    echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
                    }else{
                       // echo 'We are facing a problem right now we will contact you shortly!!';
                        $_SESSION['fail_msg']="We are facing a problem right now we will contact you shortly!!";
                        echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
                    }
                }else {
            //echo 'Email could not be sent. Try after some time';
            $_SESSION['fail_msg']="Email could not be sent. Try after some time";
            echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
        }
            }else{
                //echo 'Please fill in all the fields';
                $_SESSION['fail_msg']="Please fill in all the fields";
                echo("<meta http-equiv=\"refresh\" content=\"0;URL='bsendmail.php'\">");
}}
        }
        if(isset($_POST['submit']))
        {
            email();
        }
        
 ?>